### ISSUE TITLE
Shared element transition animation ImageView with color

### ISSUE THREAD

**Issue by daimonkor** [googlesamples/android-unsplash#10]
2 layouts xml have similar ImageView

```
<ImageView
        android:id="@+id/icon_imageView"
        android:layout_width="100dp"
        android:layout_height="100dp"           
        android:transitionName="@string/change_image_trans"          
        android:src="@android:color/darker_gray" />
```

and problem is [blinking imageview](https://www.dropbox.com/s/f0hi55w122783g6/device-2017-09-27-231719.mp4?dl=0)

**Comment by keyboardsurfer** [comment]
Thank you for this bug report. I don't see how this is related to the sample in question. Please specify.

**Comment by daimonkor** [comment]
Sorry, my fail, I spent more time for feedback you https://www.dropbox.com/s/4m2rscjgotxx2ip/ShareTransition.7z?dl=0

**Comment by keyboardsurfer** [comment]
Again, thank you. This is not an issue with this sample and a question suited for StackOverflow instead.
