### ISSUE TITLE
Move TextResize transition to upstream Support or Design package

### ISSUE THREAD

**Issue by arturdryomov** [googlesamples/android-unsplash#11]
`TextResize` `Transition` seems to be very useful in real life, but it feels wrong to copy-paste it into a project just like that. Is it possible to move it to upstream dependency where everyone can use this method?

**Comment by nickbutcher** [comment]
Perhaps check out https://github.com/shazam/reflow-animator

**Comment by arturdryomov** [comment]
Thanks, we’ll take a look!

**Comment by arturdryomov** [comment]
I’ve tried the Reflow Text Animator, but unfortunately it isn’t suited for transitions. It does not allow capturing values and animating them, but instead requires two already laid out `View` instances unfortunately. Still think that the `TextResize` can be useful as a separate or `design-` library.
