### ISSUE TITLE
SharedElement and custom EnterTransition causes memory leak

### ISSUE THREAD

**Issue by zhongjhATC** [googlesamples/android-unsplash#12]
I'm from China. My English is not very good. I'm very sorry.

The following is from the report ：
In com.example.android.unsplash:1.0:1.
* com.example.android.unsplash.DetailActivity has leaked:
* GC ROOT android.os.ResultReceiver$MyResultReceiver.this$0
* references android.app.ExitTransitionCoordinator.mResultReceiver
* references android.app.EnterTransitionCoordinator.mEnterViewsTransition
* references android.transition.TransitionSet.mParent
* references android.transition.TransitionSet.mListeners
* references java.util.ArrayList.array
* references array java.lang.Object[].[1]
* references android.transition.TransitionManager$MultiListener$1.val$runningTransitions (anonymous subclass of android.transition.Transition$TransitionListenerAdapter)
* references android.util.ArrayMap.mArray
* references array java.lang.Object[].[2]
* references com.android.internal.policy.PhoneWindow$DecorView.mContext
* leaks com.example.android.unsplash.DetailActivity instance

Use Leaks records，Keep going in and out of DetailActivity

**Comment by zhongjhATC** [comment]
https://stackoverflow.com/questions/32698049/sharedelement-and-custom-entertransition-causes-memory-leak

this didn't work for me

**Comment by codingjeremy** [comment]
This issue has been migrated to the new animations repo: [github.com/android/animation](https://github.com/android/animation).
