### ISSUE TITLE
Module 'android-unsplash' is not backed by gradle

### ISSUE THREAD

**Issue by raybesiga** [googlesamples/android-unsplash#5]
When I import the project to Android Studio from Version Control, it throws the following error:

```
Module 'android-unsplash' is not backed by gradle
```

My efforts to fix the issue have not worked. Good help will be appreciated.

**Comment by keyboardsurfer** [comment]
Cannot reproduce. [settings.gradle](https://github.com/googlesamples/android-unsplash/blob/master/settings.gradle) contains module `app`.
