### ISSUE TITLE
Dynamically update color of status bar for each image and use light status bar for contrast

### ISSUE THREAD

**Issue by amilcar-andrade** [googlesamples/android-unsplash#6]
@keyboardsurfer @nickbutcher 
Hi, I was watching the [material improvements](https://www.youtube.com/watch?v=EjTJIDKT72M) video and I though it would be cool to use the Palette to detect what should be the color of the status bar and weather or not use the light status bar. I implemented a prototype but I want to know if you think is valuable to add that feature into this sample app. Attached is a gif showing the behavior.
![giphy 6](https://cloud.githubusercontent.com/assets/802308/16212518/403696ea-3716-11e6-9f76-dbc6b93182fc.gif)

**Comment by keyboardsurfer** [comment]
Thanks for the question and the feature proposal.
This seems like a meaningful addition to the currently existing transitions.
Before you go ahead and create a pull request, I'll have to push some changes that involve a ViewPager in the DetailActivity.
I'll update the issue here once the code is pushed to GitHub.

**Comment by amilcar-andrade** [comment]
OK, let me know. Thanks @keyboardsurfer

**Comment by keyboardsurfer** [comment]
I've pushed the [commit](https://github.com/googlesamples/android-unsplash/commit/5f001bbfa72e0ef18d13b98b829ab2b9f97add88) introducing the changes I was talking about.

**Comment by amilcar-andrade** [comment]
@keyboardsurfer cool, I will get the latest changes and try to finish this week my proposal.

**Comment by amilcar-andrade** [comment]
@keyboardsurfer I have an unrelated question to this issue. But inside `PhotoAdapter` you are saving the `Activity host` and I though that saving a reference to an activity was a bad practice, is this case the exception?

**Comment by amilcar-andrade** [comment]
@keyboardsurfer never mind, you need it for all the animations. I think @nickbutcher is doing the same for Plaid, I saw this comment `// we need to hold on to an activity ref for the shared element transitions :/` inside `FeedAdapter`

**Comment by keyboardsurfer** [comment]
I've checked this and decided to make a change, so there now are less objects being created. Instead of having one OnClickListener per item, there's now an OnItemTouchListener for the whole RecyclerView.

**Comment by keyboardsurfer** [comment]
Closing this issue as it's been stale for a while.
Feel free to re-open once you find the time to work on this.

**Comment by amilcar-andrade** [comment]
Sorry @keyboardsurfer for not finishing this :(
