### ISSUE TITLE
where is PhotoItemBinding?

### ISSUE THREAD

**Issue by lijingchang** [googlesamples/android-unsplash#8]

**Comment by nickbutcher** [comment]
This class is generated by the [data binding library](https://developer.android.com/topic/libraries/data-binding/index.html), see:

https://github.com/googlesamples/android-unsplash/blob/master/app/src/main/java/com/example/android/unsplash/ui/grid/PhotoAdapter.java#L48
https://github.com/googlesamples/android-unsplash/blob/master/app/src/main/res/layout/photo_item.xml#L17
